spring.datasource.url: jdbc:mysql://localhost/onanis
spring.datasource.username: root
spring.datasource.password: password
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.batch.job.enabled: false